kubeagi/ops-console

- src/pages/EditModelService/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: update parameter baseUrl->url

- packages/dataset-version-list/src/__constants.js
- packages/dataset-version-list/src/index.jsx
- src/__constants.js
- src/pages/Dataset/index.jsx
- src/pages/DatasetVersionDetail/index.css
- src/pages/DatasetVersionDetail/index.jsx
> fix: fix some dataset issues

- src/pages/ModelAppList/index.css
- src/pages/ModelAppList/index.jsx
- src/pages/ModelWarehouseCreate/index.jsx
- src/pages/ModelWarehouseDetail/index.jsx
- src/pages/ModelWarehouseEdit/index.jsx
- src/pages/ModelWarehouseList/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
optimize model-app and model-ware-house styles based on UI
> style: optimize model-app and model-ware-house styles based on UI

- package.json
- packages/KubeAGIUpload/package.json
- packages/KubeAGIUpload/src/index.jsx
- pnpm-lock.yaml
- src/pages/CreateDataHandle/index.css
- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleDetail/index.tsx
- src/pages/DataHandleList/index.jsx
- src/pages/ModelWarehouseDetail/index.jsx
- \[x] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: add error_msg icon and tooltip
fix: upload-component request headers add namespace
> fix and feat

- src/pages/DataSetCreate/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: add displayName to DataSetCreate

- packages/KubeAGIUpload/package.json
- packages/KubeAGIUpload/src/index.jsx
- src/pages/DatasetVersionDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: dataset upload issue

- src/pages/ModelServiceDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
以上问题在低代码平台中未能复现，在portal中可以复现
1.服务模型状态下线中OfflineInProgress，在低代码中有个空格，但是能够正常识别运行，在portal中无法识别
2.变量没有规范定义，低代码平台中正常运行，portal中报错 
3.setTimeout this指向问题。低代码平台无须绑定，portal中this需要绑定
> [fix]: fix some bugs on model-service-detail page

- package.json
- pnpm-lock.yaml
- src/pages/DataHandleDetail/index.tsx
- src/pages/DataHandleList/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: data-handle detail page add log
> feat: data-handle detail page add log

- package.json
- pnpm-lock.yaml
- src/pages/CreateModelService/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: create ray model service

- src/pages/Chat/Chat/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: chat - remove debug in conversation

- src/pages/CreateModelService/index.jsx
- src/pages/EditModelService/index.jsx
- src/pages/ModelService/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: update ray model service

- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleDetail/DataHandle.tsx
- src/pages/DataHandleDetail/info.tsx
- src/pages/ModelWarehouseCreate/index.jsx
- src/pages/ModelWarehouseDetail/index.css
- src/pages/ModelWarehouseDetail/index.jsx
- src/pages/ModelWarehouseList/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: fix some bugs on data-handle and modelwarehouse
> fix: fix some bugs on data-handle and modelwarehouse

- packages/dataset-version-list/package.json
- packages/dataset-version-list/src/index.jsx
- src/__constants.js
- src/pages/Dataset/index.jsx
- src/pages/DatasetVersionDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: data issue

- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Body/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: fix can not delete knowledgebase

- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleDetail/DataHandle.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: data-handle bug
> fix: data-handle bug

- src/pages/DataSetCreate/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: fix dataset version undefined

- src/pages/CreateModelService/index.jsx
- src/pages/EditModelService/index.jsx
- src/pages/ModelService/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: model service bug fix

- src/pages/ModelServiceDetail/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: fix some bugs on model-service-detail page

- config/routes.js
- packages/KubeAGIUpload/src/index.jsx
- packages/dataset-version-list/src/index.jsx
- src/pages/DatasetVersionDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: dataset & upload issue

- package.json
- pnpm-lock.yaml
- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleList/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: data-handle list page support retry api and create api add field
> feat: data-handle list page support retry api and create api add field

- src/pages/DataSetCreate/index.jsx
- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Header/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: fix styles and validator dataset name

- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Body/ConfigPrompt/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
添加 Prompt 模板及 Prompt 介绍
> feat: add prompt template

- src/pages/CreateDataHandle/index.jsx
- src/pages/ModelAppList/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[x] ♻️ refactor
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: create model-app add init icon
refactor: create data-handle api remove bucket_name field
> feat & refactor

- src/pages/Chat/Chat/index.less
- src/pages/Chat/Chat/index.tsx
- src/pages/Chat/useConversationList/index.less
- src/pages/Chat/useConversationList/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix chat issues

- src/pages/ModelServiceDetail/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> refactor: Optimize the display of the title on model-service-detail page

- src/pages/CreateDataHandle/index.jsx
- src/pages/ModelAppList/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: fix some bugs on data-handle and model-app
> fix: fix some bugs on data-handle and model-app

- package.json
- pnpm-lock.yaml
- src/pages/Chat/Chat/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: some chat issue

- src/pages/Chat/Chat/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: chat issue

- src/pages/DatasetVersionDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: dataset version detail upload issue

- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleList/index.jsx
- src/pages/ModelAppList/index.jsx
- src/pages/ModelWarehouseDetail/index.jsx
- src/pages/ModelWarehouseList/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: fix some bugs on data-handle、 model-app、model-warehouse
> fix: fix some bugs on data-handle、 model-app、model-warehouse

- src/pages/ModelAppList/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
style: add a dialogue entry to the model-app list page
> style: add a dialogue entry to the model-app list page

- package.json
- pnpm-lock.yaml
- src/pages/CreateModelService/index.jsx
- src/pages/EditModelService/index.jsx
- src/pages/ModelService/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: model service bug fix2

- src/pages/Chat/Chat/References/index.less
- src/pages/Chat/Chat/References/index.tsx
- src/pages/Chat/Chat/References/renderContent.tsx
- src/pages/Chat/Chat/helper.tsx
- src/pages/Chat/Chat/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat show references

- src/pages/ModelAppList/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: modify model-app status text and color
ref:#156
> fix: modify model-app status text and color

- src/pages/CreateModelService/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: models select bug fix

- src/pages/Chat/Chat/index.tsx
- src/pages/Chat/useConversationList/index.less
- src/pages/Chat/useConversationList/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat - conversation delete

- src/pages/ModelAppDetail/Body/ConfigModelService/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- src/pages/ModelAppDetail/Body/index.tsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
1. 智能体配置保存按钮文字及样式调整
2. 智能体配置过滤掉非正常状态的模型服务
> style: change modal app config style

- config/api.sample.ts
- config/config.local.ts
- src/components/hooks/useGetCommonData.ts
- src/pages/Chat/Chat/index.tsx
- src/pages/Chat/useConversationList/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: using relative addresses to request api

- src/pages/ModelAppDetail/Header/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
添加智能体评估跳转连接
> feat: add assessment link

- src/pages/ModelAppDetail/Body/index.tsx
- src/pages/ModelAppDetail/Header/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: add validate form

- package.json
- pnpm-lock.yaml
- src/pages/ModelAppDetail/Body/ConfigModelService/index.tsx
- src/pages/ModelAppDetail/Body/RealTimeSearch/index.tsx
- src/pages/ModelAppDetail/Body/ViewReference/index.tsx
- src/pages/ModelAppDetail/Body/ViewResInfo/index.tsx
- src/pages/ModelAppDetail/Body/index.tsx
- src/pages/ModelAppDetail/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
智能体配置：查看响应信息，查看引用，问题引导
> feat: add custom config to app model detail

- src/pages/CreateModelService/index.jsx
- src/pages/EditModelService/index.jsx
- src/pages/ModelService/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
ref: #158
> fix: modelservice bugfix

- src/pages/ModelAppDetail/Body/ConfigPrompt/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
Prompt 模板添加 history
> feat: add history to Prompt template

- src/pages/ModelAppDetail/Body/ConfigNext/index.tsx
- src/pages/ModelAppDetail/Body/ViewReference/index.tsx
- src/pages/ModelAppDetail/Body/ViewResInfo/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- src/pages/ModelAppDetail/Body/index.tsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> style: change modal app detail height

- src/pages/Chat/useConversationList/index.less
- src/pages/Chat/useConversationList/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: change some style

- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Body/Modal/index.tsx
- src/pages/ModelAppDetail/Body/RealTimeSearch/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- src/pages/ModelAppDetail/Body/index.tsx
- src/pages/ModelAppDetail/Body/linkage.ts
- src/pages/ModelAppDetail/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
智能体配置
1. 添加实时搜索
2. 知识库，实时搜索 跟 查看引用联动处理
> feat: add RealTimeSearch and linkageReference

- package.json
- pnpm-lock.yaml
- src/pages/ModelAppList/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: form add category field
> feat: form add category field

- package.json
- pnpm-lock.yaml
- src/pages/ModelAppDetail/Header/Publish/index.less
- src/pages/ModelAppDetail/Header/Publish/index.tsx
- src/pages/ModelAppDetail/Header/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
发布智能体功能
> feat: add publish modal app

- package.json
- pnpm-lock.yaml
- src/pages/Chat/Chat/helper.tsx
- src/pages/Chat/Chat/index.less
- src/pages/Chat/Chat/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat - show referenceInfo 

- package.json
- pnpm-lock.yaml
- src/pages/Chat/Chat/References/index.tsx
- src/pages/Chat/Chat/References/renderContent.tsx
- src/pages/Chat/Chat/index.tsx
- src/pages/DatasetVersionDetail/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: dataset & chat support online data

- packages/CreateDataSource/src/index.jsx
- src/pages/DataSource/index.tsx
- src/pages/DataSourceCreate/index.tsx
- src/pages/DatasourceDetail/index.jsx
- src/pages/ModelAppDetail/Header/Edit/index.tsx
- src/pages/ModelAppDetail/Header/Publish/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
1. 发布智能体描述调整
2. 创建数据源隐藏间隔配置
3. 数据源详情支持 web 类型
4. 编辑智能体添加分类
> feat: add category to model app detail

- src/pages/Chat/Chat/PromptStarter/index.less
- src/pages/Chat/Chat/PromptStarter/index.tsx
- src/pages/Chat/Chat/index.tsx
- src/pages/Chat/useConversationList/index.less
- src/pages/Chat/useConversationList/index.tsx
- \[x] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix chat list flash issue & chat add prompt-start

- src/pages/ModelAppDetail/Header/Edit/index.tsx
- src/pages/ModelAppDetail/Header/Publish/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
发布智能体传参添加分类
> fix: add category to publish modal app

- src/pages/Chat/Chat/ChatInputBottomAddons/index.less
- src/pages/Chat/Chat/ChatInputBottomAddons/index.tsx
- src/pages/Chat/Chat/helper.tsx
- src/pages/Chat/Chat/index.less
- src/pages/Chat/Chat/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat - support for sending attachments when chat

- src/pages/Chat/Chat/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: chat with attachments issues

- src/pages/Chat/Chat/index.tsx
…mode
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat with attachments - use streamingMode instead of blockingMode

- package.json
- pnpm-lock.yaml
- src/pages/AiAgentAssessmentList/index.jsx
- src/pages/AiAgentAssessmentReport/Report.tsx
- src/pages/AiAgentAssessmentReport/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: support AiAgentAssessment report api
> feat: support AiAgentAssessment report api

- src/pages/CreateDataHandle/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: create data-handle add QA remove duplicate config
> feat: create data-handle add QA remove duplicate config

- .kiwi/en-US/DataHandle.ts
- .kiwi/zh-CN/DataHandle.ts
- src/pages/CreateAiAgentAssessment/index.jsx
- src/pages/CreateDataHandle/index.css
- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleDetail/DataHandle.tsx
- src/pages/ModelAppList/index.jsx
- src/pages/ModelWarehouseList/index.jsx
- \[x] ✨ feat
- \[x] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: adjust pageSize
feat: CreateAiAgentAssessment on Knowledge Base Judgment
feat: adjust data-handle QA remove duplicate style and interactive
style: create data-handle page compatible with dark mode
> style: create data-handle page compatible with dark mode

- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Body/ConfigPrompt/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- src/pages/ModelAppDetail/Body/index.tsx
- src/pages/ModelAppDetail/Body/linkage.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
解决进入页面，不打开知识库弹框，知识库删不掉 
close: #218
> fix: fix knowledgebase form undefined

- src/pages/ModelAppList/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: remove icon required verification
> fix: remove icon required verification

- src/pages/ModelAppDetail/Body/ConfigModelService/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
worker 类型的模型服务也需要有模型参数
> fix: add worker model

- src/pages/AiAgentAssessmentReport/Report.tsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
style: adjust radarChart style
> style: adjust radarChart style

- src/pages/ModelServiceDetail/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: add display of model-info on model-service-detail page

- src/pages/AiAgentAssessmentReport/Report.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: fix scatter plot data error
ref:#223
> fix: fix scatter plot data error

- package.json
- pnpm-lock.yaml
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
解决 loading 样式问题
> fix: change iconPrefixCls

- src/pages/ModelWarehouseCreate/index.jsx
- src/pages/ModelWarehouseDetail/index.jsx
- src/pages/ModelWarehouseEdit/index.jsx
- src/pages/ModelWarehouseList/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: add Renanking type model
ref: #235
> feat: add Renanking type model

- src/pages/ModelAppDetail/Body/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: ModalAppDetail style issue

- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Body/ConfigPrompt/index.tsx
- src/pages/ModelAppDetail/Body/Container/index.tsx
- src/pages/ModelAppDetail/Body/Plugins/index.tsx
- src/pages/ModelAppDetail/Header/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
智能体详情
1. 添加状态
2. prompt 提示修改
3. 样式调整
4. 插件新增
> feat: add status

- packages/chat/package.json
- packages/chat/src/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat with attachments api changed

- packages/chat/.fatherrc.ts
- packages/chat/README.md
- packages/chat/package.json
- packages/chat/src/ChatInputBottomAddons/index.tsx
- packages/chat/src/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: @yuntijs/chat: some issue

- src/pages/ModelAppDetail/Body/ConfigModelService/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: fix validator model err

- src/pages/Chat/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: Fix new conversation force refresh experience issue

- src/pages/CreateDataHandle/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] ♻️ refactor
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
refactor: create data handle  optimization
> refactor: create data handle  optimization

- .kiwi/en-US/DataHandle.ts
- .kiwi/zh-CN/DataHandle.ts
- src/pages/CreateDataHandle/index.jsx
- src/pages/DataHandleDetail/DataHandle.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat: data-handle support document chunk
> feat: data-handle support document chunk

- src/pages/CreateDataHandle/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: remove waiting prompt
> fix: remove waiting prompt

- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: filter ModalAppDetail Knowledge

- src/pages/DatasetVersionDetail/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: dataset csv: support CRUD

- src/pages/DatasetVersionDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: dataset file list paging support

- packages/chat/package.json
- packages/chat/src/PromptStarter/index.tsx
- packages/chat/src/index.tsx
- packages/chat/src/utils/request.ts
- src/utils/request.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: add namespace header

- src/pages/ModelServiceDetail/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: add the display of node on model-service-detail page

- package.json
- packages/chat/src/ChatInputBottomAddons/index.tsx
- packages/chat/src/References/index.tsx
- packages/chat/src/References/renderContent.tsx
- packages/chat/src/helper.tsx
- packages/chat/src/index.tsx
- pnpm-lock.yaml
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat support enableUploadFile & rerank_score

- packages/dataset-version-list/src/index.jsx
- src/pages/Dataset/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: dataset list: support upload file

- src/pages/ModelAppDetail/Body/ConfigConversationStarter/index.tsx
- src/pages/ModelAppDetail/Body/ConfigDialoge/index.tsx
- src/pages/ModelAppDetail/Body/ConfigPlugins/index.tsx
- src/pages/ModelAppDetail/Body/ConfigSearch/index.tsx
- src/pages/ModelAppDetail/Body/Modal/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- src/pages/ModelAppDetail/Body/index.tsx
- src/pages/ModelAppDetail/index.tsx
- \[x] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
1. 添加插件弹窗调整，支持配置插件参数
2. 个性化配置移动到对话配置中
3. 解决修改查询限制，保存按钮检测不到改动的问题
> feat: change tools modal

- package.json
- packages/CreateDataSource/src/index.jsx
- pnpm-lock.yaml
- src/pages/DataSource/index.tsx
- src/pages/DataSourceCreate/index.tsx
- src/pages/DatasourceDetail/index.jsx
- src/pages/ModelAppDetail/Header/Edit/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: add pg datasource api

- packages/dataset-version-list/src/index.jsx
- src/pages/CreateDataHandle/index.jsx
- src/pages/ModelWarehouseDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix: fix some data-handle and modelWarehouse detail issue
> fix: fix some data-handle and modelWarehouse detail issue

- package.json
- packages/chat/src/index.style.ts
- packages/chat/src/index.tsx
- pnpm-lock.yaml
- src/pages/ModelAppDetail/Body/ConfigConversationStarter/index.tsx
- src/pages/ModelAppDetail/Body/ConfigDialoge/index.tsx
- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.less
- src/pages/ModelAppDetail/Body/ConfigKnowledge/index.tsx
- src/pages/ModelAppDetail/Body/ConfigModelService/index.tsx
- src/pages/ModelAppDetail/Body/ConfigNext/index.tsx
- src/pages/ModelAppDetail/Body/ConfigPrompt/index.tsx
- src/pages/ModelAppDetail/Body/ConfigSearch/index.tsx
- src/pages/ModelAppDetail/Body/Container/index.less
- src/pages/ModelAppDetail/Body/Container/index.tsx
- src/pages/ModelAppDetail/Body/DocNullReturn/index.tsx
- src/pages/ModelAppDetail/Body/Modal/index.tsx
- src/pages/ModelAppDetail/Body/ViewReference/index.tsx
- src/pages/ModelAppDetail/Body/ViewResInfo/index.tsx
- src/pages/ModelAppDetail/Body/index.tsx
- src/pages/ModelAppDetail/Header/Edit/index.tsx
- src/pages/ModelAppDetail/Header/MetaData/index.tsx
- src/pages/ModelAppDetail/Header/Publish/index.tsx
- src/pages/ModelAppDetail/Header/index.less
- src/pages/ModelAppDetail/Header/index.tsx
- src/pages/ModelAppDetail/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
1. 智能体基本信息仅保留：状态、创建人、最近更新时间
2. 新增【基本信息】按钮，点击弹窗查看其余信息
3. 智能体新增“推荐”操作
4. 只有“已发布”的智能体，才可进行对话
5. “已发布”状态的智能体不可编排和编辑
6. ops 与 gpts 对话打通
> feat: add recomended and gpts chart link

- src/pages/ModelAppList/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] ♻️ refactor
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
refactor(ModelAppList): adjust model-app category
> refactor(ModelAppList): adjust model-app category

- src/pages/ModelAppDetail/Body/ConfigPlugins/index.tsx
- src/pages/ModelAppDetail/Body/index.less
- src/pages/ModelAppDetail/Header/Edit/index.tsx
- src/pages/ModelAppDetail/Header/MetaData/index.tsx
- src/pages/ModelAppDetail/Header/Publish/index.tsx
- src/pages/ModelAppDetail/Header/index.less
- src/pages/ModelAppDetail/Header/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: change isRecomended to isRecommended

- src/pages/ModelWarehouseDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix(ModelWarehouseDetail): skipHtml
> fix(ModelWarehouseDetail): skipHtml

- src/pages/ModelAppList/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix(model-app): fix edit modal data not backfilled
close:#295
> fix(model-app): fix edit modal data not backfilled

- src/pages/DatasourceDetail/index.jsx
- src/pages/ModelAppDetail/Header/Edit/index.tsx
- \[x] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
智能体分类改为从 api 获取 close: #293 
修复数据源详情数据展示问题 close: #294
> feat: add listGptCategory api

- src/pages/ModelAppList/index.jsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
feat(modelApp): Add classification filtering to the list
> feat(modelApp): Add classification filtering to the list

- src/pages/CreateAiAgentAssessment/index.jsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] ♻️ refactor
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
refactor(CreateAiAgentAssessment): update form init value
> refactor(CreateAiAgentAssessment): update form init value

- package.json
- packages/chat/package.json
- pnpm-lock.yaml
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
> chore: bump arcadia-bff-sdk@1.2.14

- packages/chat/package.json
- packages/chat/src/ChatInputBottomAddons/index.tsx
- packages/chat/src/components/getApplication.tsx
- packages/chat/src/index.tsx
- packages/chat/src/utils/kiwi/en-US/Chat.ts
- packages/chat/src/utils/kiwi/zh-CN/Chat.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> feat: chat in gpts using gpts API

- src/pages/ModelAppDetail/Body/Dialogue/index.tsx
- src/pages/ModelAppDetail/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
智能体详情接口未传参
> fix: fix name and namespace undefined

- packages/chat/package.json
- packages/chat/src/PromptStarter/index.tsx
- packages/chat/src/helper.tsx
- packages/chat/src/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: gpts fetch issue

- packages/dataset-version-list/src/__constants.js
- src/__constants.js
- src/pages/Dataset/index.css
- src/pages/Dataset/index.jsx
- src/pages/DatasetVersionDetail/index.css
- src/pages/DatasetVersionDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: dataset style issue

- src/pages/ModelWarehouseDetail/index.jsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix(ModelWarehouseDetail): fix get README.md API parameter error
close:#296
> fix(ModelWarehouseDetail): fix get README.md API parameter error

- src/pages/ModelAppDetail/Body/ConfigModelService/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
解决模型只有一个 model 时，编辑智能体 model undefined 的问题 close: #326
> fix: fix model undefied

- packages/chat/package.json
- packages/chat/src/helper.tsx
- packages/chat/src/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
> fix: send file issue in gpts
